Jdp220102 14
piotr-grosicki/project-jdp-2201-02 pull request #10
Opened 2022-02-01 20:12 UTC by Kacyper

2022-02-02 10:19 UTC, Silwiaa requested changes
zmień proszę typ idCart w Cart i CartDto na Long. Wiem, że tak daliśy w bazie, ale widzę, że reszta używa Longa.

2022-02-02 15:27 UTC, Kacyper commented
zmieniłem.

2022-02-02 15:58 UTC, Silwiaa approved these changes

2022-02-02 21:45 UTC, Silwiaa commented
@Kacyper i jak tam naprawa pulla?:)

2022-02-02 22:35 UTC, Kacyper commented
> @Kacyper i jak tam naprawa pulla?:)

Nie idzie 😡

Będę dalej to męczyć. Może kiedyś się uda.

2022-02-03 18:55 UTC, Silwiaa commented
> > @Kacyper i jak tam naprawa pulla?:)
> 
> Nie idzie 😡
> 
> Będę dalej to męczyć. Może kiedyś się uda.

a zerknij na Cart - masz tam 2x @NotNull. Może to powoduje problem

2022-02-04 08:03 UTC, piotr-grosicki requested changes
konflikty

2022-02-04 08:04 UTC, piotr-grosicki commented on build.gradle
> +//sourceCompatibility = 1.8
ta linijka nie powinna zostac zakomentowana

2022-02-04 17:24 UTC, piotr-grosicki requested changes

2022-02-04 17:24 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +import jdk.jfr.Unsigned;
to nie dziala w hibernate

2022-02-04 17:24 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
> +import jdk.jfr.Unsigned;
tutaj tez

2022-02-04 17:24 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +import jdk.jfr.Unsigned;
tutaj rowniez

2022-02-04 17:24 UTC, piotr-grosicki commented on src/main/resources/application.properties
> +#spring.jpa.hibernate.naming.strategy=org.hibernate.cfg.ImprovedNamingStrategy
nie wysylamy na gita zakomentowanego kodu

2022-02-04 18:22 UTC, KusibabPiotr requested changes

2022-02-04 18:22 UTC, KusibabPiotr commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
potrzebujemy pola name, price, productDescription :)

2022-02-04 18:40 UTC, KusibabPiotr approved these changes

2022-02-04 18:40 UTC, merged