New Group entity created
piotr-grosicki/project-jdp-2201-02 pull request #11
Opened 2022-02-01 20:55 UTC by kpikula

New Group entity class to be merged

2022-02-02 11:58 UTC, piotr-grosicki requested changes
projekt sie nie buduje

2022-02-02 15:30 UTC, DudekJakub requested changes
Hej. 

Po pobraniu sobie Twoje pull-requesta i próbie zbudowania projektu wyskakuje błąd:
java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; [...]

W skrócie chodzi o to, że SQL ma pewne słowa-klucze, które są zarezerwowane dla wewnętrznych operacji w bazie danych i nie mogę być bezpośrednio użyte np. właśnie podczas tworzenia encji. 
Polecam wpisać sobie w google "why is group reserved word in sql" i wyskoczy Ci skrócony opis problemu. ;)

Rozwiązaniem jest zmiana nazwy encji z:
@Entity(name = "GROUPS" )
na
@Entity(name = "\"GROUPS\"")

W tym momencie słowo kluczowe nie jest wyłapywane i cyk, projekt się buduje.

2022-02-02 18:18 UTC, kpikula commented
I revised the Group entity and added the Product class to enable grandlew build

2022-02-02 20:01 UTC, piotr-grosicki requested changes

2022-02-02 20:01 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
> +@Entity(name = "GROUPSX")
nazwa nie powinna zawierac litery X, spojrz dokladnie jak Jakub napisal ;)

2022-02-02 21:13 UTC, kpikula commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
> +@Entity(name = "GROUPSX")
OK, changed

2022-02-04 08:04 UTC, piotr-grosicki submitted a review, later dismissed
konflikty

2022-02-04 17:44 UTC, DudekJakub approved these changes
Changes accepted

2022-02-04 17:52 UTC, KusibabPiotr approved these changes

2022-02-04 17:52 UTC, KusibabPiotr commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +
żeby wszystko ładnie wyglądało nie potrzeba robic spacji :)

2022-02-04 17:55 UTC, merged