WIP JDP220102-23
piotr-grosicki/project-jdp-2201-02 pull request #18
Opened 2022-02-03 19:20 UTC by Silwiaa

createCart() method in CartController updated with real implementation. 
Added CartNotFoundException and  GlobalHttpErrorHandler (will be needed with next CartController methods).
Because of the need for having Cart entity for CartRepository interface I created it and filled only with Id. Rest will be continued in JDP220102-14.
I added saveCart() in DbServiceCart and mapToCart() in CartMapper

2022-02-04 08:04 UTC, piotr-grosicki requested changes
konflikty

2022-02-04 10:40 UTC, Silwiaa commented
> konflikty

@piotr-grosicki konflikty rozwiązane

2022-02-04 16:59 UTC, piotr-grosicki requested changes

2022-02-04 16:59 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +  private BigDecimal total;
w tej encji nie powinno byc zadnych zmian, to zadanie polega na napisaniu controllera

2022-02-04 17:02 UTC, piotr-grosicki requested changes

2022-02-04 17:02 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/service/DbServiceCart.java
> +        System.out.println(deleteMessage);
nie wyswietlamy takich informacji korzystajac z System.out.println(). Wszystkie bledy powinny zostac wyrzucone jako wyjatki z odpowiednim kodem http

2022-02-04 17:02 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/GlobalHttpErrorHandler.java
> +        return new ResponseEntity<>("Cart with given id doesn't exist or can't be found", HttpStatus.BAD_REQUEST);
NOT_FOUND zamiast BAD_REQUEST

2022-02-04 21:13 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +  private BigDecimal total;
poprawione

2022-02-04 21:49 UTC, Basixx approved these changes

2022-02-04 22:19 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/controller/GlobalHttpErrorHandler.java
> +        return new ResponseEntity<>("Cart with given id doesn't exist or can't be found", HttpStatus.BAD_REQUEST);
poprawione

2022-02-04 22:56 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/service/DbServiceCart.java
> +        System.out.println(deleteMessage);
poprawione

2022-02-05 20:11 UTC, KusibabPiotr requested changes
ogólnie @NotNull sie nie powinno dać bo nie bedzie sie dalo zapisac do bazy - skoro nie ustawisz id to Cart sie nie utworzy bo jest pole not null czyli nie moze by puste ale to przegadamy na grupie :) nie obraź się sory za tyle komentów ;)

2022-02-05 20:11 UTC, KusibabPiotr commented on src/main/java/com/kodilla/ecommercee/service/DbServiceCart.java
> +        BigDecimal currentTotalFromCart = cart.getTotal();
ta metoda powinna wygladac tak ze wybierasz z bazy Cart i wybierasz z bazy Produkt a potem ten produkt dodajesz do tej Cart ktore wyciągnelas z bazy :)

2022-02-05 20:11 UTC, KusibabPiotr commented on src/main/java/com/kodilla/ecommercee/service/DbServiceCart.java
> +        cartRepository.findById(idCart).get().getProducts().removeIf(n -> n.getId() == idProduct);
ogolnie wg mnie tylko ta linijka jest potrzebna, ale zamiast get() użyj orElseThrow()

2022-02-06 09:51 UTC, Silwiaa commented
> ogólnie @NotNull sie nie powinno dać bo nie bedzie sie dalo zapisac do bazy - skoro nie ustawisz id to Cart sie nie utworzy bo jest pole not null czyli nie moze by puste ale to przegadamy na grupie :) nie obraź się sory za tyle komentów ;)

2022-02-06 09:52 UTC, Silwiaa commented
> ogólnie @NotNull sie nie powinno dać bo nie bedzie sie dalo zapisac do bazy - skoro nie ustawisz id to Cart sie nie utworzy bo jest pole not null czyli nie moze by puste ale to przegadamy na grupie :) nie obraź się sory za tyle komentów ;)

@KusibabPiotr w której części kodu?

2022-02-06 09:54 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
>      @PostMapping(consumes = MediaType.APPLICATION_JSON_VALUE)
zostawiam - tam mamy w materiałach + taką konwencję stosują też inni w pozostałych kontrolerach

2022-02-06 09:57 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
>      public void createCart(@RequestBody CartDto cartDto) {
zostawiam - w zadaniu z projektu "Tasks" createTask() zwraca void

2022-02-06 09:57 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +        dbServiceCart.saveCart(cart);
zostawiam j/w

2022-02-06 10:10 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +            return products.stream()
poprawione

2022-02-06 10:10 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +            System.out.println("Cart with id: " + idCart + " doesn't exist or can't be found");
poprawione

2022-02-06 10:11 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +            System.out.println("Cart with id: " + idCart + " doesn't exist or can't be found");
zdublowany komentarz

2022-02-06 10:29 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/service/DbServiceCart.java
> +        if (dbServiceProduct.ifExist(idProduct)) {
poprawione

2022-02-06 10:30 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/service/DbServiceCart.java
> +            productPrice = product.get().getPrice();
nie rozumiem komentarza - proce nigdy nie będzie nullem

2022-02-06 10:31 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/service/DbServiceCart.java
> +        } else {
poprawione

2022-02-06 11:33 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/service/DbServiceCart.java
> +        BigDecimal currentTotalFromCart = cart.getTotal();
poprawione

2022-02-06 11:49 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/service/DbServiceCart.java
> +        cartRepository.findById(idCart).get().getProducts().removeIf(n -> n.getId() == idProduct);
poprawione

2022-02-06 11:57 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
zostawiam - ProductController jeszcze w pull request

2022-02-06 11:58 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/domain/ProductDto.java
> +    private Long idGroup;
nie kumam o co Ci chodzi - poprawimy ewentualne konflikty

2022-02-06 12:07 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/mapper/CartMapper.java
> +        return new Cart(
poprawione

2022-02-06 12:07 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/mapper/CartMapper.java
> +        return new CartDto(
poprawione

2022-02-06 12:11 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/service/DbServiceCart.java
> +    public boolean ifExist (final Long idCart) {
zostawiam - nie widzę sensu wywoływać obiektu cart getProductsFromCart jeżeli potrzebuje jedynie wiedzieć czy takowy istnieje i nic z nim więcej nie robię

2022-02-06 12:12 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/service/DbServiceCart.java
> +        List<Product> products = cartRepository.findById(idCart).get().getProducts();
wiem, ze istnieje bo przekazałam w cartControlerze z metodą ifExist. Zostawiam

2022-02-06 19:21 UTC, KusibabPiotr requested changes

2022-02-06 19:21 UTC, KusibabPiotr commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +        dbServiceCart.saveCart(cart);
w tym konkretnym przypadku rzeczywiście nie ma po co zwracać utworzonej dopiero co - pustej karty :)

2022-02-06 19:21 UTC, KusibabPiotr commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +        if (dbServiceCart.ifExist(idCart)) {
jeśli chodzi o if else w kontrolerze to można to działanie ukryć w serwisie :)
daj znać jak bedziesz na skype to Ci wyjaśnie myśle że bedzie to dużo ładniej wyglądać. Pozatym powinnas rzucic błąd jak nie znajdziesz karty o danym numerze a nie zwracać pustą liste bo to mylące dla przyszłego użytkownika

2022-02-06 19:21 UTC, KusibabPiotr commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
>      @PostMapping(value = "/createOrder/{idCart}")
nie rozumie sensu tej metody. Już masz metodę @Post tworzaca nowa karte a w tej metodzie mapowanie mowi że chcesz utworzyć nowy Order ale to neii jest Order Controller.

2022-02-06 19:21 UTC, KusibabPiotr commented on src/main/java/com/kodilla/ecommercee/domain/ProductDto.java
> +    private Long idGroup;
zamiast Long idGroup jest pole Group group :)

2022-02-06 19:21 UTC, KusibabPiotr commented on src/main/java/com/kodilla/ecommercee/service/DbServiceCart.java
> +        List<Product> products = cartRepository.findById(idCart).get().getProducts();
https://klolo.github.io/blog/2017/08/05/jak-uzywac-optional/

2022-02-06 20:24 UTC, KusibabPiotr approved these changes

2022-02-06 20:26 UTC, merged