Added Order entity
piotr-grosicki/project-jdp-2201-02 pull request #19
Opened 2022-02-03 20:54 UTC by donzdanowicz

2022-02-04 08:05 UTC, piotr-grosicki requested changes
konflikty

2022-02-04 18:06 UTC, KusibabPiotr commented
usuń @Unsigned i rozwiąż konflikt w Cart

2022-02-04 18:08 UTC, KusibabPiotr requested changes

2022-02-04 18:08 UTC, KusibabPiotr commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +
brak zależności do produktów :)

2022-02-04 18:28 UTC, KusibabPiotr requested changes

2022-02-04 18:28 UTC, KusibabPiotr commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +    private double shippingPrice;
użyj big decimal zamiast double :)

2022-02-04 18:28 UTC, KusibabPiotr commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +    private double totalPrice;
użyj big decimal zamiast double :)

2022-02-05 18:39 UTC, KusibabPiotr approved these changes

2022-02-05 18:55 UTC, Basixx approved these changes

2022-02-05 18:55 UTC, merged