created real implementation of product controller + service + reposit…
piotr-grosicki/project-jdp-2201-02 pull request #20
Opened 2022-02-04 16:43 UTC by KusibabPiotr

…ory + mapper(need to add GroupEntity mapping later when it ll be ready, i commented for a time b) changes to productDto contains new group settlements

I'd like to ask you to cancel JDP220102-21 pull request. i added all changes in this one.

2022-02-04 21:30 UTC, Basixx requested changes

2022-02-04 21:30 UTC, Basixx commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +
Czy w tym miejscu nie powinno pojawić się wywołanie obiektu klasy ProductMapper? 
Np "private final ProductMapper productMapper;"? A później w metodach użyty właśnie ten wywołany obiekt?
Jeśli Twój sposób jest poprawny chętnie się o niego podpytam, bo wcześniej się nie spotkałam z takim użyciem. Mam też wrażenie, że wywołanie obiektu na górze klasy może być trochę bardziej konsekwentne, jeśli zrobiłeś tak dla DbServiceProduct :)

2022-02-04 21:30 UTC, Basixx commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +        return ProductMapper.mapToDto(serviceProduct.getProduct(id));
Między innymi o tę linijkę mi chodzi z productMapper.

2022-02-04 21:30 UTC, Basixx commented on src/main/java/com/kodilla/ecommercee/mapper/ProductMapper.java
> +//                .group() need Group mapper implementation
Z tego co zrozumiałam napisanie Mappera to jedna z części tego zadania. Nie widzę go w tym commicie, jest gdzieś wcześniej?

2022-02-04 21:30 UTC, Basixx commented on src/main/java/com/kodilla/ecommercee/mapper/ProductMapper.java
> +//                .group() need Group mapper implementation
Jeśli reszta osób zatwierdzi ten kod, będzie chyba trzeba dodać ten fragment osobnym branchem, tak jak rozmawialiśmy na spotkaniu :)

2022-02-05 19:03 UTC, Basixx approved these changes

2022-02-06 12:19 UTC, donzdanowicz commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +
Wygląda na to, że Piotrek użył tu metody statycznej, dlatego nie wywołuje obiektu klasy ProductMapper w tym miejscu.

2022-02-06 12:23 UTC, donzdanowicz commented on src/main/java/com/kodilla/ecommercee/mapper/ProductMapper.java
> +
Nie powinno tu być adnotacji @Service? Tak jest w kursie w TaskMapper.

2022-02-06 12:41 UTC, donzdanowicz commented on src/main/java/com/kodilla/ecommercee/repository/ProductRepository.java
> +    List<Product> findAll();
Nie nadpisujesz tu metod save, deleteById, findById ?
Rozwiązujesz to jakoś inaczej? 

w kursie : 
@Override
    Task save(Task task);

    @Override
    void deleteById(Long taskId);

    @Override
    Optional<Task> findById(Long id);

2022-02-06 12:42 UTC, donzdanowicz commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +        return ProductMapper.mapToDto(serviceProduct.getProduct(id));
jak wyżej

2022-02-06 12:53 UTC, donzdanowicz commented on src/main/java/com/kodilla/ecommercee/repository/ProductRepository.java
> +
Nie powinieneś tu zrobić adnotacji
@Repository?

2022-02-06 12:56 UTC, donzdanowicz requested changes
Komentarze w ProductController, ProductMapper, ProductRepository.

2022-02-06 13:23 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/repository/ProductRepository.java
> +    List<Product> findAll();
@donzdanowicz nie trzeba. Te metody są zawarte w klasie CrudRepository. Też pytałam mentora po co robimy @Override - uzyskałam odpowiedź, że żeby wskazać z których będziemy korzystać, ale nie jest to obowiązkowe

2022-02-06 13:30 UTC, donzdanowicz commented on src/main/java/com/kodilla/ecommercee/repository/ProductRepository.java
> +    List<Product> findAll();
Aha, dzięki. Skoro tak, to w porządku.

2022-02-06 20:00 UTC, donzdanowicz approved these changes
Changes approved.

2022-02-06 21:18 UTC, merged