JDP220102-33 - Korekta encji Product.java.
piotr-grosicki/project-jdp-2201-02 pull request #28
Opened 2022-02-08 16:36 UTC by Kacyper

2022-02-08 17:28 UTC, Silwiaa requested changes

2022-02-08 17:28 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
>  @Entity(name = "products")
zamień proszę na drukowane PRODUCTS - tak mamy w innych encjach

2022-02-08 17:28 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +    @OneToMany(
@OneToMany do usuniecia (czyli linie 32-37). Produkty są w relacji one to many z grupami - i mamy to już w liniach 37-30.

2022-02-08 17:28 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/domain/ProductDto.java
>      private GroupDto groupDto;
ta linia jest zbędna

2022-02-08 17:28 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/service/DbServiceCart.java
> +//        BigDecimal totalPrice = countTotalPrice(shippingPrice, cart.getProducts());
czemu to jest zakomentowane?

2022-02-08 17:28 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/service/DbServiceCart.java
> +//    private BigDecimal countTotalPrice(BigDecimal shippingPrice, List<Product> products) {
czemu linie 66-71 są zakomentowane?

2022-02-08 20:53 UTC, DudekJakub requested changes

2022-02-08 20:53 UTC, DudekJakub commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +    @OneToMany(
Hej, o ile nie mieszają mi się już w głowie te wszystkie relacje między encjami, to żeby być dokładnym, Nasze produkty są w relacji ManyToOne z grupami. Wiele produktów w jednej grupie <-> jedna grupa z wieloma produktami.

Z resztą się zgadzam, generalnie Kacper stworzyłeś w encji Product relację... produktu z produktami. ;P

2022-02-08 20:53 UTC, DudekJakub commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
>      @ManyToMany(cascade = CascadeType.ALL,
Tu wg. mnie trzeba będzie zmienić CascadeType.ALL. Dlaczego? Otóz CascadeType.ALL zawiera w sobie wszystkie funkcje tzw. EntityMenagera, który z kolei zarządza Naszymi encjami. Jego operacje to:
- PERSIST
- REFRESH 
- MERGE
- DETACH 
i najbardziej Nas w tym momencie interesująca:
- REMOVE

Poprzez operacje REMOVE w momencie usunięcia koszyka, usunie się też powiązany w relacji z nim produkt. Jeżeli w obu relacjach będziemy mieli ALL, to zarówno Rodzic relacji, jak i Dziecko relacji będą się wzajemnie usuwać. 
Rodzica (Parent) relacji ustawiamy tam, gdzie wpisujemy "mappedBy". :) 

Obecnie zajmuje się testowaniem encji Product, nie rozkminiłem jeszcze na 100% jak ma to być poprawnie ustawione, więc więcej nie pomogę na chwilę obecną.

2022-02-08 20:59 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +    @OneToMany(
@DudekJakub nie no ale @OneToMany musi być ustawione w grupie a @ManyToOne w Produkcie. Więc nie wszystkie relacje do usuniecia

2022-02-09 16:48 UTC, Kacyper commented on src/main/java/com/kodilla/ecommercee/service/DbServiceCart.java
> +//        BigDecimal totalPrice = countTotalPrice(shippingPrice, cart.getProducts());
ze względu na to, że odwołuje się do counttotalprice, które korzysta z getprice, a je wyrzuciliśmy z produktu. dlatego zakomentowałem je by nie usuwać. inteli wali na czerwono błędem o braku metody, bo nie ma się do czego odwołać. dlatego zamiast usuwać zakomentowałem.

2022-02-09 16:50 UTC, Kacyper commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
>      @ManyToMany(cascade = CascadeType.ALL,
w takim razie to zostaje na razie w próżni?

2022-02-10 18:41 UTC, Silwiaa requested changes

2022-02-10 19:01 UTC, Kacyper commented on src/main/java/com/kodilla/ecommercee/service/DbServiceCart.java
> +//        BigDecimal totalPrice = countTotalPrice(shippingPrice, cart.getProducts());
Miałem chwilkę to tak zrobiłem by pokazać, że to nie działa. Projekt się nie buduje przez to. Tam jest odwołanie właśnie do price w product, ale to wywalamy z klasy więc to nie przejdzie w tej postaci w DbServiceCart w tych metodach o ile się ich nie usunie. Komentowałem by nie usuwać by sobie sprawdzić w razie coś.
<img width="1556" alt="Screenshot 2022-02-10 at 19 58 11" src="https://user-images.githubusercontent.com/70667144/153478110-e191657a-f601-4f50-a068-909c2fd55e58.png">

2022-02-10 19:07 UTC, Silwiaa requested changes

2022-02-11 22:35 UTC, closed without merging