Jdp220102 18
piotr-grosicki/project-jdp-2201-02 pull request #29
Opened 2022-02-08 18:37 UTC by KusibabPiotr

tests for Group entity

2022-02-08 20:25 UTC, Basixx requested changes
Mógłbyś dodać jeszcze kilka testów dotyczących relacji z Encją Product. Czy przypisanie produktu do grupy zadziała. Co się stanie gdy usuniemy jeden produkt dodany do grupy, albo grupę, w której są produkty. Imo założenie jest takie, że usunięcie produktu nie może usuwać grupy (bo jeśli od dziś nie sprzedaję mleka, to nie znaczy, że nie sprzedaję nabiału) natomiast usunięcie grupy powinno powodować usunięcie wszystkich produktów (bo jeśli od dziś nie sprzedajemy nabiału, to nie sprzedajemy jajek, mleka itp)

2022-02-08 20:25 UTC, Basixx commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
>      @GeneratedValue(strategy = GenerationType.IDENTITY)
Z tego co się orientuję, umówiliśmy się na @NotNull i @GeneratedValue(strategy = GenerationType.AUTO) nad ID

2022-02-08 20:25 UTC, Basixx commented on src/main/java/com/kodilla/ecommercee/repository/GroupRepository.java
> +    List<Group> findAll();
Uważam, że przydałby się tu jeszcze Override metody save

2022-02-08 20:25 UTC, Basixx commented on src/test/java/com/kodilla/ecommercee/repository/GroupRepositoryTest.java
> +        groupRepository.deleteAll();
Bezpieczniejszym sposobem na CleanUp jest usuwanie po ID

2022-02-08 20:49 UTC, KusibabPiotr commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
>      @GeneratedValue(strategy = GenerationType.IDENTITY)
wysyłałem Ci artykuł o tym ze do mysql używa się IDENTITY :) a @NotNull jest

2022-02-08 20:49 UTC, KusibabPiotr commented on src/main/java/com/kodilla/ecommercee/repository/GroupRepository.java
> +    List<Group> findAll();
@Override
    List<Group> findAll(); << po to się pisze override bo ta metoda zwraca normalnie Iterable<Group> i żeby nie rzutować.
Zasada jest taka żeby nie dopisywać niepotrzebnego kodu a wym wypadku kod nic nie zmienia

2022-02-08 20:49 UTC, KusibabPiotr commented on src/test/java/com/kodilla/ecommercee/repository/GroupRepositoryTest.java
> +        assertThat(group.getProducts().size()).isEqualTo(0);
ten test ma sprawdzac tylko czy grupa się zapisała jak wskazuje nazwa testu :)

2022-02-08 20:49 UTC, KusibabPiotr commented on src/test/java/com/kodilla/ecommercee/repository/GroupRepositoryTest.java
> +        groupRepository.deleteAll();
w mojej opini jest takie samo działanie a lepiej nie robić bloków try catch przy usuwaniu po id ale proszę o wytłumaczenie twojej tezy:)

2022-02-08 20:49 UTC, KusibabPiotr commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
>      @GeneratedValue(strategy = GenerationType.IDENTITY)
a tak w ogóle to nie ja robiłem group encje :) dodałem tylko @Buildera

2022-02-09 12:32 UTC, KusibabPiotr reviewed
Basiu, dodałem 2 nowe metody które sprawdzaja czy produkty dodają się do grupy i czy można je usunąć. Co do 3 metody o która prosiłaś to jej nie potrzeba gdyż po prostu nie da się usunąć grupy jesli są do niej przypisane jakiekolwiek produkty. Jest to spowodowane tym ze produkt posiada Id - jako klucz obcy w bazie.

2022-02-09 13:15 UTC, KusibabPiotr commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
>      @GeneratedValue(strategy = GenerationType.IDENTITY)
https://thorben-janssen.com/5-things-you-need-to-know-when-using-hibernate-with-mysql/

2022-02-09 20:37 UTC, donzdanowicz commented on src/main/java/com/kodilla/ecommercee/repository/GroupRepository.java
> +
niepotrzebne wcięcie - warto usunąć

2022-02-09 20:38 UTC, donzdanowicz commented on src/main/java/com/kodilla/ecommercee/repository/GroupRepository.java
> +    List<Group> findAll();
Generalnie wygląda na to, że większością grupy podjęliśmy decyzję, żeby nie pisać Override'ów innych metod i ja też dostałem taką uwagę w tasku. Mentor mówił, że w tym przypadku to niepotrzebne.

2022-02-09 20:39 UTC, donzdanowicz commented on src/test/java/com/kodilla/ecommercee/repository/GroupRepositoryTest.java
> +
niepotrzebne wcięcie - warto usunąć

2022-02-09 20:39 UTC, donzdanowicz commented on src/test/java/com/kodilla/ecommercee/repository/GroupRepositoryTest.java
> +
niepotrzebne wcięcie - warto usunąć

2022-02-09 20:42 UTC, donzdanowicz commented on src/test/java/com/kodilla/ecommercee/repository/GroupRepositoryTest.java
> +public class GroupRepositoryTest {
Konwencja w kursie i widzę też na przykład u Kasi jest, żeby używać XRepositoryTestSUITE, a nie XRepositoryTest, także proponuję dla spójności projektu to zmienić.

2022-02-09 20:43 UTC, donzdanowicz commented on src/test/java/com/kodilla/ecommercee/repository/GroupRepositoryTest.java
> +        groupRepository.deleteAll();
Wydaje mi się, że nie powinieneś usuwać w teście wszystkich danych używając deleteAll().

"Pisząc test jednostkowy nie należy polegać na własnym stanie bazy danych. Co to oznacza? Nie zakładaj, że wszyscy w bazie mają takie same dane. Test powinien być uniwersalny – nie możesz zakładać, że po dodaniu do bazy jednego z rekordów, będzie on jedynym wpisem w danej tabeli. Czyszcząc dane po wykonaniu testu, nie usuwaj wszystkiego z bazy danych. Wyczyść tylko te dane, które Twój test utworzył w trakcie działania."

2022-02-09 20:57 UTC, donzdanowicz requested changes
Jak w komentarzach

2022-02-10 10:00 UTC, KusibabPiotr commented on src/test/java/com/kodilla/ecommercee/repository/GroupRepositoryTest.java
> +
już usuwam wcięcia :)

2022-02-10 10:09 UTC, KusibabPiotr commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
>      @GeneratedValue(strategy = GenerationType.IDENTITY)
a co do Auto czy Identity tak naprawde do tej pory używałem MySql i H2 a tam identity jest preferowaną opcją ale jeśli Auto działa mi wszystko jedno :)

2022-02-12 01:15 UTC, DudekJakub requested changes
Kod należy zaktualizować w związku ze zmianami wprowadzony przez ostatnie 2 dni (encje - relacje).

2022-02-12 16:28 UTC, Silwiaa commented
@KusibabPiotr daj znać jak będzie gotowe do sprawdzenia

2022-02-15 14:58 UTC, Basixx requested changes
Testy dotyczące usuwania można usunąć. Wiem że wcześniej mówiłam, że ich brakuje, ale sama po spotkaniu z mentorem i ustaleniu, że nie przewidujemy usuwania recordów musiałam wywalić 4 testy ze swojego zadania.

2022-02-15 14:58 UTC, Basixx commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
> -            cascade = CascadeType.ALL,
Po spotkaniu z mentorem poszła decyzja, że nie przewidujemy usuwania, więc ALL może zostać, bo nic nie zepsuje

2022-02-15 14:58 UTC, Basixx commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> -    @NotNull
Umówiliśmy  się że zostaje @NotNull i Auto, we wszystkich innych encjach właśnie tak jest i tak działa.

2022-02-15 14:58 UTC, Basixx commented on src/main/java/com/kodilla/ecommercee/repository/GroupRepository.java
> +    List<Group> findAll();
Macie rację, mea culpa

2022-02-15 18:49 UTC, kpikula commented on src/test/java/com/kodilla/ecommercee/repository/GroupRepositoryTestSuite.java
> +    public void testDeleteGroup(){
Mamy nie testować usuwania, bo takiej funkcji ma nie być

2022-02-15 18:54 UTC, kpikula commented on src/test/java/com/kodilla/ecommercee/repository/GroupRepositoryTestSuite.java
> +    public void testAddProductsToGroupAndDeleteProduct(){
Do usunięcia z powodu jw.

2022-02-15 18:55 UTC, kpikula commented on src/test/java/com/kodilla/ecommercee/repository/GroupRepositoryTestSuite.java
> +        groupRepository.deleteAll();
Jeden wiersz do usunięcia, bo cascade = CascadeType.ALL

2022-02-15 18:56 UTC, kpikula requested changes
Kilka uwag

2022-02-15 19:24 UTC, KusibabPiotr commented on src/test/java/com/kodilla/ecommercee/repository/GroupRepositoryTestSuite.java
> +        groupRepository.deleteAll();
nie da rady tak :) jeśli usuniesz produkty grupy zostaja, a nie możesz usunąć grupy puki sa w niej produkty >> constrainty

2022-02-15 19:28 UTC, KusibabPiotr commented on src/test/java/com/kodilla/ecommercee/repository/GroupRepositoryTestSuite.java
> +        assertThat(all.get(0).getProducts().get(0).getName()).isEqualTo("Produkt");
tak naprawde oba testy sprawdzaja czy produkt został dodany do grupy - mój jest nawet dokladniejszy bo sprawdza czy to napewno ten dodany produkt :) ale rzeczywiście to wszystko jedno

2022-02-15 19:29 UTC, KusibabPiotr commented on src/test/java/com/kodilla/ecommercee/repository/GroupRepositoryTestSuite.java
> +    public void testAddProductsToGroupAndDeleteProduct(){
o ten test prosiła mnie @Basixx  to już sam nie wiem :)

2022-02-15 20:28 UTC, donzdanowicz commented on src/test/java/com/kodilla/ecommercee/repository/GroupRepositoryTestSuite.java
> +        groupRepository.deleteAll();
zauważ, że najpierw usuwasz wszystkie produkty, a potem grupy. Nie jest tak, że usuwając wszystkie produkty, to przy usuwaniu grupy masz już puste grupy bez produktów, więc usuną się też grupy?

2022-02-15 20:30 UTC, donzdanowicz commented on src/test/java/com/kodilla/ecommercee/repository/GroupRepositoryTestSuite.java
> +        productRepository.delete(product);
dałbym do //When, ale to tylko taka luźna sugestia

2022-02-15 20:33 UTC, donzdanowicz commented on src/test/java/com/kodilla/ecommercee/repository/GroupRepositoryTestSuite.java
> +        groupRepository.deleteAll();
a w ogóle widzę teraz, że w tym commicie jednak usunąłeś cascade = CascadeType.ALL

2022-02-15 20:33 UTC, donzdanowicz submitted a review, later dismissed
jak w komentarzach

2022-02-16 12:51 UTC, KusibabPiotr commented on src/test/java/com/kodilla/ecommercee/repository/GroupRepositoryTestSuite.java
> +        groupRepository.deleteAll();
no żeby usunąć grupy trzeba usunąć produkty inaczej jest Constraint w postaci klucza obcego - ściągnij sobie kod i obczaj sam ;) cascade type usunąłem w grupach bo jest niepotrzebne i zabezpiecz nas w przyszlosci ze ktos jak usunie grupy nie polecą powiązane produkty - teraz trzeba usuwać produkty zeby usunąć grupe takie jest poprawne zachowanie

2022-02-16 18:54 UTC, donzdanowicz commented
zrobiłem update do maina i circleci mówi, że projekt się nie buduje.

2022-02-17 06:41 UTC, KusibabPiotr commented on src/test/java/com/kodilla/ecommercee/repository/GroupRepositoryTestSuite.java
> +    public void testAddProductsToGroupAndDeleteProduct(){
usuniętę..

2022-02-19 10:56 UTC, kpikula commented on src/test/java/com/kodilla/ecommercee/repository/GroupRepositoryTestSuite.java
> +        Group save1 = groupRepository.save(newGroup2);
Zmiennych "save" i "save1" nigdzie nie używasz

2022-02-19 11:01 UTC, kpikula commented on src/test/java/com/kodilla/ecommercee/repository/GroupRepositoryTestSuite.java
> +        assertThat(group.getProducts().size()).isEqualTo(0);
Po co to sprawdzać w teście wyszukiwania po id?

2022-02-19 11:04 UTC, KusibabPiotr commented on src/test/java/com/kodilla/ecommercee/repository/GroupRepositoryTestSuite.java
> +        Group save1 = groupRepository.save(newGroup2);
racja ;) robiłem różne kombinacje z testami i zostało

2022-02-19 11:05 UTC, KusibabPiotr commented on src/test/java/com/kodilla/ecommercee/repository/GroupRepositoryTestSuite.java
> +        assertThat(group.getProducts().size()).isEqualTo(0);
tez zostało po prywatnych testach testów heeh

2022-02-19 12:37 UTC, kpikula approved these changes

2022-02-19 13:57 UTC, Basixx approved these changes

2022-02-19 14:01 UTC, Kacyper approved these changes

2022-02-19 16:15 UTC, DudekJakub approved these changes

2022-02-19 16:38 UTC, merged