Task JDP220102-20 (User entity tests + build) new
piotr-grosicki/project-jdp-2201-02 pull request #31
Opened 2022-02-08 22:24 UTC by kpikula

2022-02-09 12:45 UTC, Silwiaa requested changes

2022-02-09 12:45 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/repository/OrderRepository.java
enter do usuniecia

2022-02-09 12:45 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/repository/UserRepository.java
> +
tu tez

2022-02-09 12:45 UTC, Silwiaa commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +
enter do usuniecia

2022-02-09 12:45 UTC, Silwiaa commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +
tu też. Dodatkowo zamieniłabym na java.util.* i java.time.* żeby zmniejszyć ilość importów

2022-02-09 12:45 UTC, Silwiaa commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +    UserRepository userRepository;
brakuej modyfikatora dostepu

2022-02-09 12:45 UTC, Silwiaa commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +    OrderRepository orderRepository;
tu również

2022-02-09 12:45 UTC, Silwiaa commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +        try {
nie wiem czy możemy pominąć zapis //CleanUp. Ale to do obgadania

2022-02-09 12:45 UTC, Silwiaa commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +        List<User> userList = userRepository.findAll();
wg mnie powinno iść do //Then

2022-02-09 12:45 UTC, Silwiaa commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +        userRepository.save(user);
powinno iść do //Given

2022-02-09 12:45 UTC, Silwiaa commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +        int numberOfUserOrders = user.getOrders().size();
sprawdziłabym przed i po usunięciu - tak jak w poprzednim teście

2022-02-09 12:45 UTC, Silwiaa commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +
sprawdziłabym ile było przed usunięciem

2022-02-09 12:45 UTC, Silwiaa commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +        User user = User.builder()
rozważyłąbym próbę przygotowaina before testów ponieważ dane w //Given się powtarzają

2022-02-09 12:53 UTC, kpikula commented on src/main/java/com/kodilla/ecommercee/repository/OrderRepository.java
Ta linia powstaje, gdy automatycznie formatuję projekt (Ctrl+L). Oddziela grupę importów.

2022-02-09 12:54 UTC, kpikula commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +
Ta linia powstaje, gdy automatycznie formatuję projekt (Ctrl+L). Oddziela grupę importów.

2022-02-09 17:51 UTC, donzdanowicz commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +            userRepository.deleteAll();
Wydaje mi się, że nie powinnaś usuwać w teście wszystkich danych używając deleteAll().

"Pisząc test jednostkowy nie należy polegać na własnym stanie bazy danych. Co to oznacza? Nie zakładaj, że wszyscy w bazie mają takie same dane. Test powinien być uniwersalny – nie możesz zakładać, że po dodaniu do bazy jednego z rekordów, będzie on jedynym wpisem w danej tabeli. Czyszcząc dane po wykonaniu testu, nie usuwaj wszystkiego z bazy danych. Wyczyść tylko te dane, które Twój test utworzył w trakcie działania."

2022-02-09 17:53 UTC, donzdanowicz commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +        try {
W wypadku zapisu try, finally ciężko stwierdzić, gdzie umieścić //CleanUp, ale zgadzam się, że powinien być.
Inna sprawa, czy powinno się używać metody try, finally z pominięciem Catch?

2022-02-09 17:54 UTC, donzdanowicz commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +            userRepository.deleteAll();
jak wyżej, "Czyszcząc dane po wykonaniu testu, nie usuwaj wszystkiego z bazy danych."

2022-02-09 17:58 UTC, donzdanowicz commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +
o jedno wcięcie za dużo ;)

2022-02-09 18:25 UTC, kpikula commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +        List<User> userList = userRepository.findAll();
To kwestia preferencji, a ja trzymam się jednej konwencji we wszystkich testach

2022-02-09 18:25 UTC, kpikula commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +        int numberOfUserOrders = user.getOrders().size();
OK, tak zrobię

2022-02-09 18:28 UTC, kpikula commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +
OK, tak zrobię

2022-02-09 18:28 UTC, kpikula commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +        User user = User.builder()
Celna uwaga, zastanowię się nad tym:-)

2022-02-09 18:29 UTC, kpikula commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +            userRepository.deleteAll();
OK, przemyślę to

2022-02-09 18:29 UTC, kpikula commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +            userRepository.deleteAll();
OK, przemyślę to

2022-02-09 18:29 UTC, kpikula commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +
na koniec zrobię Ctrl+L i będzie w porządku

2022-02-09 18:32 UTC, kpikula commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +
IntelliJ sam to ogranicza, oczywiście można samemu wpisywać, ale z automatu lista jest zawężana

2022-02-09 20:51 UTC, donzdanowicz commented on src/main/java/com/kodilla/ecommercee/repository/OrderRepository.java
> +    @Override
Z różnych reakcji grupy rozumiem, że nie trzeba nadpisywać metod innych od findAll() 

Grupa mówi:
"@OverRide
po to się pisze override bo ta metoda zwraca normalnie Iterable i żeby nie rzutować.
Zasada jest taka żeby nie dopisywać niepotrzebnego kodu a w tym wypadku kod nic nie zmienia"

"nie trzeba. Te metody są zawarte w klasie CrudRepository. Też pytałam mentora po co robimy Override - uzyskałam odpowiedź, że żeby wskazać z których będziemy korzystać, ale nie jest to obowiązkowe"

2022-02-09 22:41 UTC, Silwiaa commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +
no tak, ale po co nam tyle linijek w imporcie. W kursie też podpowiadają żeby dać java.util.*

2022-02-09 22:41 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/repository/OrderRepository.java
ok

2022-02-09 22:42 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/repository/UserRepository.java
> +
ok

2022-02-10 08:24 UTC, piotr-grosicki commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +        List<User> userList = userRepository.findAll();
tutaj sie nie zgodze z tym :) to nie jest kwestia preferencji tylko logika blokow `given`, `when`, `then`. 

Test sprawdza zapis uzytkownika, wiec w sekcji given spodziewalbym sie przygotowania encji, w sekcji when zapisu a w sekcji then sprawdzenia pobrania userow i sprawdzenia czy wszystko sie zapisalo tak jak sie spodziewalismy

Podzial na given, when, then powinien byc logiczny i zrozumialy dla kazdego z programistow tak aby testy dalo sie latwo odczytac

2022-02-10 08:26 UTC, piotr-grosicki commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +        user.getOrders().add(order1);
to nie sprawdza czy ordery dodaja sie do usera, poniewaz dokonujesz zapisu usera PRZED dodaniem ich do listy. Ten zapis jedynie sprawdza czy lista w javie dziala :)

2022-02-10 08:26 UTC, piotr-grosicki commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +        user.getOrders().remove(order1);
to samo tutaj, sprawdzasz logike dzialania list w javie, nie sprawdzajac czy encja w bazie danych poprawnie sie zachowuje

2022-02-10 09:43 UTC, kpikula commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +    UserRepository userRepository;
OK, uzupełniłam

2022-02-10 09:43 UTC, kpikula commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +        List<User> userList = userRepository.findAll();
OK, wezmę pod uwagę

2022-02-10 09:44 UTC, kpikula commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +        userRepository.save(user);
OK, wezmę pod uwagę

2022-02-10 18:44 UTC, Silwiaa commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +    UserRepository userRepository;
nie widze zmiany

2022-02-12 01:15 UTC, DudekJakub requested changes
Kod należy zaktualizować w związku ze zmianami wprowadzony przez ostatnie 2 dni (encje - relacje).

2022-02-12 16:28 UTC, Silwiaa commented
@kpikula daj znać jak będzie gotowe do sprawdzania

2022-02-13 23:32 UTC, Silwiaa requested changes

2022-02-13 23:32 UTC, Silwiaa commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +        Long id = user.getId();
chyba mocno będę optować za przeniesieniem linii 45 do //Then
Na moją logikę test mówi: kiedy zapiszę usera to...
jeśli zostawimy id tutaj będzie mówił "kiedy id równa się...

i to mi nie pasuje totalnie

2022-02-13 23:32 UTC, Silwiaa commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +    public void createNewUserTest() {
test dotyczy zapisania usera w bazie, nie stworzenia. Myślę, że nazwa do zmiany na testSaveUser()

2022-02-13 23:32 UTC, Silwiaa commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +        assertEquals("Kate", user1UserName);
ta asercja nie sprawdza istoty testu.

2022-02-13 23:32 UTC, Silwiaa commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +        //Given
powinno być od małej litery. Nie wiem też czy test nie powinno być pierwsze (z tego co kumam to nazwy powinny odzwierciedlać czynność a nie być bezokolicznikami). Jednak nie dam sobie ręki uciąć. Czyli testUpdateUser (testuje updatowanie usera) zamiast testowanie updatu usera.

2022-02-13 23:32 UTC, Silwiaa commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +
linia 105 powinna iść do //when: kiedy ustawię na false i zapiszę to...

2022-02-13 23:32 UTC, Silwiaa commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +        //Given
duża litera do poprawy + nic nie mówi ta nazwa - zmieniłabym na coś w stylu testCreateOrderForUser() lub testSaveUserWithOrder()

2022-02-13 23:32 UTC, Silwiaa commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +        orderRepository.save(order);
tu nie jestem pewna - ale czy nie powinniśmy dodawać orderu do usera a nie odwrotnie? Raz, że tak wskazuje logika zakupów a dwa, że testujemy tu encję User a nie order.
Wtedy user.setOrder(order) i userRepository.save(user) powinno iść do //When

2022-02-13 23:32 UTC, Silwiaa commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +        LocalDate orderDate = users.get(0).getOrders().get(0).getOrderDate();
na pewno nie powinno to być w //When

2022-02-13 23:32 UTC, Silwiaa commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +        //Given
od małej + nic nie mówi nazwa testu

2022-02-13 23:32 UTC, Silwiaa commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +
174 i 175 powinny iść do //When - są istotą testu

2022-02-13 23:32 UTC, Silwiaa commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +        //Given
od małej

2022-02-13 23:32 UTC, Silwiaa commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +
skoro istotą testu jest delete to nie powinno to być w given. Dodatkowo umówiliśmy się na soft delete

2022-02-14 10:14 UTC, kpikula commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +    public void createNewUserTest() {
Zmienię nazwę na save

2022-02-14 10:15 UTC, kpikula commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +        Long id = user.getId();
OK

2022-02-14 10:19 UTC, kpikula commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +        //Given
OK

2022-02-14 10:20 UTC, kpikula commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +
OK

2022-02-14 10:22 UTC, kpikula commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +        LocalDate orderDate = users.get(0).getOrders().get(0).getOrderDate();
OK

2022-02-14 10:23 UTC, kpikula commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +
OK

2022-02-14 10:23 UTC, kpikula commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +
test usunięty

2022-02-14 10:25 UTC, kpikula commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +        //Given
OK

2022-02-14 10:27 UTC, kpikula commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +        assertEquals("Kate", user1UserName);
Moim zdaniem sprawdza. Sprawdza, czy można znaleźć użytkownika po ID. Użytkownik o ID 1 (findById(1L)) to użytkownik o nazwie "Kate"

2022-02-14 11:36 UTC, Silwiaa requested changes

2022-02-14 11:36 UTC, Silwiaa commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +        assertEquals("Kate", user1UserName);
tak, ale tutaj sprawdzasz czy username usera 1 jest Kate a nie czy metoda findById znalazła użytkownika. Zmieniłabym na:
w given user 2 w ogóle nie jest potrzebny
do when 
 Long id = user1.getId()
 readUser = userRepository.findById(id)
do then:
assertEquals(id, readUser.getId)
lub jeśli chcesz sprawdzać po nazwie (ale wydaje mi się to zbędne) to:
assertEquals(user1.getName(), readUser.getName())

2022-02-14 11:36 UTC, Silwiaa commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +
linia 178 powinna być w //Then

2022-02-14 12:26 UTC, kpikula commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +
OK

2022-02-14 17:36 UTC, DudekJakub reviewed
Hej. Krótkie wyjaśnienie, dlaczego nie chcemy korzystać z obejścia exceptionala 'LazyInitializationException' za pomocą FetchType.EAGER umieściłem na Naszym skypowym czacie.
Owe wyjaśnienie chciałem wrzucić jako 'change-requesta', ale błyskawiczny commit Kasi mnie wyprzedził. ;)

2022-02-14 19:49 UTC, donzdanowicz approved these changes
Zatwierdzam zmiany

2022-02-14 20:35 UTC, Silwiaa commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +        orderRepository.save(order);
faktycznie jest dobrze - nie zauwazylam, ze mamy relacje onetomany. Nie wiem tylko czy test nie jest redundancyjny (powieli się w order). Ale chyba mozna zostawić

2022-02-14 20:35 UTC, Silwiaa approved these changes

2022-02-14 20:36 UTC, Silwiaa commented
@piotr-grosicki prosimy o sprawdzenie lub wypisanie się z review żebyśmy mogli zaakceptowac:)

2022-02-15 12:43 UTC, Silwiaa requested changes

2022-02-15 12:43 UTC, Silwiaa commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +}
projekt się nie buduje

2022-02-15 13:20 UTC, kpikula commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +}
Niestety wiem, na razie nie umiem sobie z tym poradzić

2022-02-15 18:51 UTC, Silwiaa approved these changes

2022-02-16 10:19 UTC, Silwiaa commented
@donzdanowicz @DudekJakub @piotr-grosicki prosimy o zatwierdzenie merga lub wypisanie się z review:)

2022-02-16 12:44 UTC, DudekJakub requested changes

2022-02-16 12:51 UTC, kpikula commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +        user.setCart(new Cart());
Usunęłam

> Linijka 156 jest zbędna, koszyk został już przypisany do użytkownika w linijce 150 (podczas inicjalizacji Usera).

Usunęłam

2022-02-16 12:54 UTC, DudekJakub commented on src/test/java/com/kodilla/ecommercee/repository/UserEntityTestSuite.java
> +        user.setCart(new Cart());
Jesteś pewna, że przesłałaś commita? :)

2022-02-16 12:59 UTC, merged