JDP220102 19
piotr-grosicki/project-jdp-2201-02 pull request #40
Opened 2022-02-13 03:25 UTC by Basixx

Testy Encji Cart

2022-02-13 11:30 UTC, Silwiaa requested changes

2022-02-13 11:30 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/repository/OrderRepository.java
>  }
usaliliśmy @Override tylko dla findAll()

2022-02-13 11:30 UTC, Silwiaa commented on src/test/java/com/kodilla/ecommercee/CartRepositoryTestSuite.java
> +import org.junit.Test;
rozważyłabym zmniejszenie importów poprzez zamianę na .*

2022-02-13 11:30 UTC, Silwiaa commented on src/test/java/com/kodilla/ecommercee/CartRepositoryTestSuite.java
> +
zamieniłabym na java.util.*

2022-02-13 11:30 UTC, Silwiaa commented on src/test/java/com/kodilla/ecommercee/CartRepositoryTestSuite.java
> +
brakuje modyfikatora dostępu (private)

2022-02-13 11:30 UTC, Silwiaa commented on src/test/java/com/kodilla/ecommercee/CartRepositoryTestSuite.java
> +
tu również

2022-02-13 11:30 UTC, Silwiaa commented on src/test/java/com/kodilla/ecommercee/CartRepositoryTestSuite.java
> +
tu też

2022-02-13 11:30 UTC, Silwiaa commented on src/test/java/com/kodilla/ecommercee/CartRepositoryTestSuite.java
> +        Cart cart = Cart.builder()
niby drobnostka, ale widziałam, że inni w testach mają //Given //When //Then (czyli od dużej litery)

2022-02-13 11:30 UTC, Silwiaa commented on src/test/java/com/kodilla/ecommercee/CartRepositoryTestSuite.java
> +        //given
nazwa powinna odzwierciedlać co robi test - w tym przypadku cos w rodzaju testSaveCart()

2022-02-13 11:30 UTC, Silwiaa commented on src/test/java/com/kodilla/ecommercee/CartRepositoryTestSuite.java
> +
powinno iść do //Then

2022-02-13 11:30 UTC, Silwiaa commented on src/test/java/com/kodilla/ecommercee/CartRepositoryTestSuite.java
> +
powinno iść do //Then

2022-02-13 11:30 UTC, Silwiaa commented on src/test/java/com/kodilla/ecommercee/CartRepositoryTestSuite.java
> +       }
zaczęłabym od dużej litery

2022-02-13 11:30 UTC, Silwiaa commented on src/test/java/com/kodilla/ecommercee/CartRepositoryTestSuite.java
> +        //given
nie wiem jak się umówiliście, ale zawsze w kursie zaczynaliśmy od "test". Nie wiem też czy nie powinno być bardziej coś w rodzaju testSaveCartWithProducts()

2022-02-13 11:30 UTC, Silwiaa commented on src/test/java/com/kodilla/ecommercee/CartRepositoryTestSuite.java
> +                .build();
group nie powinna być nullem

2022-02-13 11:30 UTC, Silwiaa commented on src/test/java/com/kodilla/ecommercee/CartRepositoryTestSuite.java
> +                .build();
group nie powinno być nullem

2022-02-13 11:30 UTC, Silwiaa commented on src/test/java/com/kodilla/ecommercee/CartRepositoryTestSuite.java
> +        Long cart1Id = cart1.getId();
dałabym do //Then

2022-02-13 11:30 UTC, Silwiaa commented on src/test/java/com/kodilla/ecommercee/CartRepositoryTestSuite.java
> +        Long shampoo1Id = shampoo1.getId();
dałabym do //Then

2022-02-13 11:30 UTC, Silwiaa commented on src/test/java/com/kodilla/ecommercee/CartRepositoryTestSuite.java
> +        Long soap1Id = soap1.getId();
dałabym do //Then

2022-02-13 11:30 UTC, Silwiaa commented on src/test/java/com/kodilla/ecommercee/CartRepositoryTestSuite.java
> +        List<Product> products = productRepository.findAll();
91-92 na pewno powinno być w then. Test sprawdza savowanie i tylko to powinno być w //When

2022-02-13 11:30 UTC, Silwiaa commented on src/test/java/com/kodilla/ecommercee/CartRepositoryTestSuite.java
> +        productRepository.save(shampoo1);
powinno iść do given

2022-02-13 11:30 UTC, Silwiaa commented on src/test/java/com/kodilla/ecommercee/CartRepositoryTestSuite.java
> +        productRepository.save(soap1);
powinno iść do given

2022-02-13 11:30 UTC, Silwiaa commented on src/test/java/com/kodilla/ecommercee/CartRepositoryTestSuite.java
> +    public void userHasCart(){
zmieniłabym na testSaveUserWithCart(). Jednak w zasadzie w ogóle nie jestem pewna czy ten test powinnien tu się znajdować - bardziej mi pasuje do testowania encji user

2022-02-13 11:30 UTC, Silwiaa commented on src/test/java/com/kodilla/ecommercee/CartRepositoryTestSuite.java
> +         cartRepository.save(myCart);
powinno iść do //Given

2022-02-14 22:37 UTC, Silwiaa approved these changes

2022-02-14 22:39 UTC, DudekJakub approved these changes
Gites

2022-02-14 22:39 UTC, merged