Jdp220102 50
piotr-grosicki/project-jdp-2201-02 pull request #42
Opened 2022-02-14 23:41 UTC by Silwiaa

Poprawa implementacji CartController i zależnych mu klas

2022-02-14 23:47 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/service/DbServiceCart.java
> -        return productsSum.add(shippingPrice);
ustalono, że order będzie tworzył OrderRepository

2022-02-14 23:48 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> -
ustalono, że kartę będzie tworzył user

2022-02-14 23:48 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    @PutMapping("/{idCart}/{idProduct}")
ustalono, że order będzie tworzył OrderRepository

2022-02-15 15:08 UTC, Basixx requested changes
Jedna tycia przywalka, ogólnie wydaje się bdb  :D

2022-02-15 15:08 UTC, Basixx commented on src/main/java/com/kodilla/ecommercee/service/DbServiceCart.java
> +    public Cart updateCart(final Long idCart, final Long idProduct) throws CartNotFoundException, ProductNotFoundException, ProductNotAvailableException {
Dobrze jakby ta metoda nazywała się "addToCart" analogicznie do tej usuwającej :)

2022-02-15 16:18 UTC, Kacyper approved these changes

2022-02-15 17:33 UTC, merged