Jdp220102 58
piotr-grosicki/project-jdp-2201-02 pull request #48
Opened 2022-02-17 20:04 UTC by KusibabPiotr

* rejestracja użytkownika do aplikacji za pomocą linka w wysyłanym mailu
* dodanie swaggera do projektu
* dodanie spring security - niezbedne do logowania
* odblokowanie endpointów do swagera, rejestracji i logowania
* przygotowanie aplikacji do implementacji JWT - token umożliwiający autoryzaje po zalogowaniu >>> zadanie pkt.6

2022-02-17 21:09 UTC, Silwiaa requested changes
sam sobie to sprawdzaj:P:P:P

2022-02-17 21:09 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/controller/GlobalHttpErrorHandler.java
> +    }
na bank nie wszystkie to bad request. Zerknij na te z listy i trzeba bedzie odpowiednio przyporzadkować: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status

2022-02-17 21:09 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/controller/LoginController.java
> +    }
brakuje response entity

2022-02-17 21:09 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/controller/RegistrationController.java
> +}
wszedzie brakuje response entity

2022-02-17 21:09 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/domain/ConfirmationToken.java
> +    @JoinColumn(
wszedzie robilismy entery miedzy polami

2022-02-17 21:10 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/domain/ConfirmationToken.java
> +    @JoinColumn(
projekt sie nie buduje

2022-02-17 21:40 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/domain/ConfirmationToken.java
> +    @JoinColumn(
przy okazji roziwaz tez pls konflikty

2022-02-18 08:25 UTC, Silwiaa requested changes
@KusibabPiotr moje poprawki nie wprowadzone

2022-02-18 22:52 UTC, KusibabPiotr commented on src/main/java/com/kodilla/ecommercee/domain/ConfirmationToken.java
> +    @JoinColumn(
jutro zrobie te entery :)

2022-02-19 09:59 UTC, KusibabPiotr commented on src/main/java/com/kodilla/ecommercee/controller/GlobalHttpErrorHandler.java
> +    }
zmieniłem kilka :)

2022-02-19 10:04 UTC, KusibabPiotr commented on src/main/java/com/kodilla/ecommercee/controller/LoginController.java
> +    }
done :)

2022-02-19 10:12 UTC, KusibabPiotr commented on src/main/java/com/kodilla/ecommercee/controller/RegistrationController.java
> +}
Done ;)

2022-02-19 15:54 UTC, closed without merging

2022-02-19 15:54 UTC, KusibabPiotr commented
Something is wrong ;(
registration working but authentication of user is not!