Jdp220102 59
piotr-grosicki/project-jdp-2201-02 pull request #50
Opened 2022-02-18 15:20 UTC by Silwiaa

Poprawki UserController po testach

Zrobilam od razu maly clean code żeby już poszło - usuniecie zbednych importow, jakiś spacji, enterow i takie tam

2022-02-19 12:59 UTC, Basixx requested changes
To co napisałam w komentarzu tyczy się wielu miejsc w kodzie.

2022-02-19 12:59 UTC, Basixx commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    public ResponseEntity<CartDto> addProductToCart(@PathVariable Long idCart, @PathVariable Long idProduct) throws Exception {
Tak jak Piotr (jego komentarze na innym branchu), uważam, że te Exceptiony powinny być konkretne, nie ogólne. Chyba nie rozumiem, czemu to zmieniłaś.

2022-02-20 00:09 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    public ResponseEntity<CartDto> addProductToCart(@PathVariable Long idCart, @PathVariable Long idProduct) throws Exception {
@Basixx żeby nie robic litanii. Ale poprawie

2022-02-20 14:31 UTC, Kacyper approved these changes

2022-02-20 16:04 UTC, KusibabPiotr approved these changes

2022-02-20 16:04 UTC, merged