JDP220102-56
piotr-grosicki/project-jdp-2201-02 pull request #51
Opened 2022-02-18 17:48 UTC by Silwiaa

kolejne merge przypadkowo usunely chyba moje zmiany wiec wysylam jeszcze raz

2022-02-19 11:48 UTC, kpikula commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +    @PutMapping("/{id}/{groupName}")
Do usunięcia jest "/groupName" ze ścieżki". Po co to wpisywać skoro dopiero tworzymy grupę?

2022-02-19 11:50 UTC, kpikula commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +    @PostMapping("/{groupName}")
Do usunięcia jest "/groupName" ze ścieżki". Po co to wpisywać skoro dopiero tworzymy grupę?

2022-02-19 12:20 UTC, KusibabPiotr requested changes
tak naprawde musisz dodać .products(new ArrayList<>()) w DbServiceGroup do działania a reszta to moje uwagi kosmetyczne choć proponuje je wprowadzić :)

2022-02-19 12:20 UTC, KusibabPiotr commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +    public ResponseEntity<GroupDto> createGroup(@PathVariable String groupName) throws Exception {
albo @RequestBody z samą nazwa tak wg mnie tak powinno to wygladac. Ogólnie nie da się utworzyc grupy ale błąd jest w metodzie createGroup() klasy DbServiceGroup >> przy tworzeniu grupy w bloku else{} brakuje .products(new ArrayList<>()) << po dodaniu tej linijki wszystko działa

2022-02-19 12:20 UTC, KusibabPiotr commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +    @PutMapping("/{id}/{groupName}")
tu w url zostawiłbym tylko {id}

2022-02-19 12:20 UTC, KusibabPiotr commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +    public ResponseEntity<GroupDto> updateGroup(@PathVariable Long id, @PathVariable String groupName) throws Exception {
tak samo jak metodzie wyżej wysłałbym nowa nazwę przez @RequestParam lub @RequestBody

2022-02-19 12:20 UTC, KusibabPiotr commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
> +    public ResponseEntity<UserDto> createUser(@RequestBody UserDto userDto) throws Exception {
też konkretny wyjątek bym dal

2022-02-19 12:20 UTC, KusibabPiotr commented on src/main/java/com/kodilla/ecommercee/service/DbServiceGroup.java
> +
dodaj tutaj ".products(new ArrayList<>())"

2022-02-19 12:20 UTC, KusibabPiotr commented on src/main/java/com/kodilla/ecommercee/service/DbServiceGroup.java
> +    public Group createGroup(final String groupName) throws Exception {
throws GroupExistInRepositoryException bym dał

2022-02-19 12:20 UTC, KusibabPiotr commented on src/main/java/com/kodilla/ecommercee/service/DbServiceGroup.java
> +    public Group updateGroup(final Long id, final String groupName) throws Exception {
throws GroupExistInRepositoryException, GroupExistInRepositoryException  bym dał

2022-02-19 12:36 UTC, kpikula requested changes
Ściągnij sobie najpierw zmiany z maina, bo Twój kod jest nieaktualny w niektórych miejscach

2022-02-19 18:11 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +    public ResponseEntity<GroupDto> createGroup(@PathVariable String groupName) throws Exception {
> pasuje zwracac konkretny wyjątek w tym przypadku GroupExistInRepositoryException()

@KusibabPiotr on zwraca GroupExistInRepository(), ale poza nim również inne exception dlatego dałam typ Exception z ktorego dziedzicza zeby nie robic litanii po przecinku

2022-02-19 18:16 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/controller/GlobalHttpErrorHandler.java
> +    //Cart entity exception handlers
poprawione

2022-02-19 18:16 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/controller/GlobalHttpErrorHandler.java
> +    //Product entity exception handlers
poprawione

2022-02-19 18:17 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +    public ResponseEntity<GroupDto> createGroup(@PathVariable String groupName) throws Exception {
no ale zmienie, niech Ci bedzie:)

2022-02-19 18:51 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +    @PostMapping("/{groupName}")
poprawiono

2022-02-19 18:51 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +    public ResponseEntity<GroupDto> updateGroup(@PathVariable Long id, @PathVariable String groupName) throws Exception {
poprawiono

2022-02-19 18:52 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
> +    public ResponseEntity<UserDto> createUser(@RequestBody UserDto userDto) throws Exception {
poprawiono

2022-02-19 18:53 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/service/DbServiceGroup.java
> +    public Group updateGroup(final Long id, final String groupName) throws Exception {
poprawiono

2022-02-19 19:05 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +    public ResponseEntity<GroupDto> createGroup(@PathVariable String groupName) throws Exception {
> albo @requestbody z samą nazwa tak wg mnie tak powinno to wygladac. Ogólnie nie da się utworzyc grupy ale błąd jest w metodzie createGroup() klasy DbServiceGroup >> przy tworzeniu grupy w bloku else{} brakuje .products(new ArrayList<>()) << po dodaniu tej linijki wszystko działa

dam requestParam bo wtedy mam z głowy walidację (czy przyszedł poprawny String) i zostanie mi tylko walidacja żeby String nie był pusty

2022-02-19 19:13 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +    public ResponseEntity<GroupDto> createGroup(@PathVariable String groupName) throws Exception {
poprawiono

2022-02-19 19:27 UTC, kpikula commented on src/main/java/com/kodilla/ecommercee/controller/GlobalHttpErrorHandler.java
> +    //Cart entity exception handlers
Ja je nadal widzę

2022-02-19 19:28 UTC, kpikula commented on src/main/java/com/kodilla/ecommercee/controller/GlobalHttpErrorHandler.java
> +    //Product entity exception handlers
jw.

2022-02-19 23:57 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +    public ResponseEntity<GroupDto> updateGroup(@PathVariable Long id, @PathVariable String groupName) throws Exception {
dalam request param

2022-02-20 00:03 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/service/DbServiceGroup.java
> +
przeniosłam do mappera

2022-02-20 00:03 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/service/DbServiceGroup.java
> +    public Group createGroup(final String groupName) throws Exception {
poprawiono

2022-02-20 00:03 UTC, Silwiaa commented
> Ściągnij sobie najpierw zmiany z maina, bo Twój kod jest nieaktualny w niektórych miejscach I doszły konflikty z mainem

poprawiono

2022-02-20 00:04 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +    @PutMapping("/{id}/{groupName}")
poprawiono

2022-02-20 09:42 UTC, KusibabPiotr approved these changes

2022-02-20 10:53 UTC, Silwiaa commented
@KusibabPiotr zamieniłam w GroupDto na listę id - zobacz czy to ma sens

2022-02-20 11:01 UTC, kpikula commented on src/main/java/com/kodilla/ecommercee/mapper/GroupMapper.java
> +import com.kodilla.ecommercee.domain.Product;
Pousuwaj zbędne importy

2022-02-20 11:03 UTC, kpikula commented on src/main/java/com/kodilla/ecommercee/mapper/ProductMapper.java
> +import java.util.Optional;
import do usunięcia

2022-02-20 11:10 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/mapper/GroupMapper.java
> +import com.kodilla.ecommercee.domain.Product;
poprawiono

2022-02-20 11:10 UTC, Silwiaa commented on src/main/java/com/kodilla/ecommercee/mapper/ProductMapper.java
> +import java.util.Optional;
poprawiono

2022-02-20 11:45 UTC, kpikula approved these changes

2022-02-20 11:46 UTC, merged