GroupController + GroupDto created
piotr-grosicki/project-jdp-2201-02 pull request #6
Opened 2022-01-31 18:41 UTC by DudekJakub

Initial implementation of GroupController + GroupDto

2022-01-31 18:47 UTC, piotr-grosicki requested changes

2022-01-31 18:47 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +    @GetMapping(value = "getGroups")
to jest ustalone z grupa? widzialem w jednym controllerze troche inny sposob robienia sciezek.

Przeydskutujcie w grupie

2022-01-31 20:33 UTC, piotr-grosicki requested changes

2022-01-31 20:33 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +    public GroupDto getGroup(@RequestParam Long groupId) throws Exception {
to tak nie zadziala, musi byc `PathVariable`, to samo przy `delete`

2022-01-31 21:10 UTC, DudekJakub commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +    public GroupDto getGroup(@RequestParam Long groupId) throws Exception {
Poprawione

2022-02-02 09:10 UTC, piotr-grosicki requested changes

2022-02-02 09:10 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +    public GroupDto updateGroup(@PathVariable Long id, @RequestBody GroupDto groupDto) {
to id nie jest tutaj potrzebne, id znajduje sie juz w group dto

2022-02-02 12:44 UTC, DudekJakub commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +    public GroupDto updateGroup(@PathVariable Long id, @RequestBody GroupDto groupDto) {
Poprawione

2022-02-02 15:22 UTC, piotr-grosicki approved these changes

2022-02-02 15:23 UTC, merged